### PR TITLE
My details

### PR DESCRIPTION
**Pull request by jobin2201**

### CODE REVIEW

**Comment by gdsc-kits-admin** [comment]
Jobin

**Comment by gdsc-kits-admin** [comment]
Hey can you do the commit again, there are some issues with the build file.

**Comment by jobin2201** [comment]
i am supposed to commit again? but it was proper only. i did exactly how it
was told

**Comment by gdsc-kits-admin** [comment]
Yes, there are some issues with the build files,

*Connect. Learn. Grow*


*Renuka Rajpuria*GDSC Lead 2023-24

Karunya Institute of Technology and Sciences

Phone: 8100435794

Email: ***@***.***

**Pull request closed without merging**
