### PR TITLE
Added Swathy's profile

### PR DESCRIPTION
**Pull request by Saroj-Swadithya**

### CODE REVIEW

**Comment by SomSingh23** [comment]
@Saroj-Swadithya  please create a new branch and add your profile data to it so that all tests will pass. If you attempt to make changes to the main branch and send a pull request, the system checks will naturally fail because you are not allowed to make any changes to the main branch.

**Comment by gdsc-kits-admin** [comment]
Hey can you do the commit again, there are some issues with the build files.

**Comment by Saroj-Swadithya** [comment]
I created a new branch. But still its not working

**Comment by gdsc-kits-admin** [comment]
Hey please redo it without creating a branch.

*Connect. Learn. Grow*


*Renuka Rajpuria*GDSC Lead 2023-24

Karunya Institute of Technology and Sciences

Phone: 8100435794

Email: ***@***.***

**Pull request closed without merging**
